name = "government-jobs-portal"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets" }

[[d1_databases]]
binding = "DB"
database_name = "jobs-portal-db"
database_id = "5079071b-00d6-4c24-b8e2-c69d91517a83"
